name: Go

on: [push, pull_request]

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '^1.23', '1.x' ]
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go ${{ matrix.go }}
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go }}

    - name: version
      run: go version

    - name: Test
      run: go test ./...

    - name: Vet
      run: go vet -v ./...



